# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  # This becomes the permanent internal DNS name (http://fintech-backend)
  name: fintech-backend
  labels:
    app: fintech
    component: backend
spec:
  # Explicitly locking this down to internal traffic only
  type: ClusterIP
  selector:
    app: fintech
    component: backend
  ports:
  - port: 5000
    targetPort: 5000
